- Dockerfile
> Dockerfile: added oath-toolkit installation

- Dockerfile
- README.md
- npm-start.sh
- reload-dashboard.sh
- setup-proxy.sh
- start-ceph.sh
- stop-ceph.sh
This PR add some useful script for developers working on ceph dashboard.
> Add some scripts for ceph dashboard developers

- start-ceph.sh
> Set 'ceph dashboard set-rgw-api-user-id <user>' in start-ceph.sh

- README.md
- docker-compose.yml
This PR adds an openldap container as well as an phpldapadmin container.
> Add openldap container

- Dockerfile
- bin/reload-dashboard.sh
- bin/start-ceph.sh
- Remove mgr logs before starting/reloading vstart
- Add default env variables used by dashboard scripts
- Setup proxy after starting vstart
`Signed-off-by: Tiago Melo <tmelo@suse.com>`
> Improvements

- README.md
Fixed some script names, improved formatting.
> Updated README.rst

- Dashboards/README.md
- Dashboards/ceph-cluster.json
- Dashboards/cephfs-overview.json
- Dashboards/host-details.json
- Dashboards/osd-device-details.json
- Dashboards/pool-detail.json
- Dashboards/pool-overview.json
- Dashboards/radosgw-detail.json
- Dashboards/radosgw-overview.json
- grafana.ini
Signed-off-by: a2batic <murarkakanika@gmail.com>
> Adds Dashboard jsons and steps to see embedded grafana

- Dashboards/cephfs-overview.json
- Dashboards/host-details.json
- Dashboards/hosts-overview.json
- Dashboards/osd-device-details.json
- Dashboards/osds-overview.json
- Dashboards/pool-detail.json
- Dashboards/pool-overview.json
- Dashboards/radosgw-detail.json
- Dashboards/radosgw-overview.json
Signed-off-by: a2batic <murarkakanika@gmail.com>
> Adds new dashboard jsons for Grafana

- Dockerfile
> Install Python JWT packages

- bin/make-frontend.sh
This commands helps testing the make process of the dashboard frontend
> Add "make-frontend" command

- Dockerfile
Fixes: #34
Signed-off-by: Ricardo Dias <rdias@suse.com>
> Fix cython version to less than 0.29

- Dockerfile
This reverts commit 14dac9f7fd303b1eb27d6047438866f4b0bf90ef.
> Revert "Fix cython version to less than 0.29"

- README.md
> README: Add information regarding CEPH_PORT

- Dockerfile
> Fix problem with version of tempora

- shared/zsh/.zshrc
> Add 'activate' alias

- nautilus.Dockerfile
- setup.sh
> Add nautilus dockerfile

- README.md
Moved the Grafana section right after the Prometheus section
Minor style improvements (headline capitalizations)
> README.md: Various doc improvements

- shared/bin/create-dashboard-rgw-user.sh
This PR fixes a regression introduced in https://github.com/ricardoasmarques/ceph-dev-docker/pull/53
> Fix RGW user creation script

- README.md
- mimic.Dockerfile
- nautilus.Dockerfile
- shared/bin/mimic/setup-ceph.sh
- shared/bin/nautilus/setup-ceph.sh
- shared/zsh/.zshrc
`Signed-off-by: Tiago Melo <tmelo@suse.com>`
> Add release specific setup-ceph.sh files

- shared/bin/start-ceph.sh
> Set +r on keyring for integration with ceph-dev-vagrant

- shared/bin/npm-start.sh
- shared/zsh/.zshrc
This will fix a ghosting problem in the cli and reduce permission problems when installing packages.
> Fix 2 problems

- shared/bin/setup-modules.sh
> Add script to configure all modules with default values

- shared/bin/mimic/setup-ceph.sh
- shared/bin/nautilus/setup-ceph.sh
- shared/bin/setup-ceph.sh
> Use git clean instead of removing selected folders

- Dockerfile
- mimic.Dockerfile
- nautilus.Dockerfile
> Remove "build" environment variable

- prometheus/alert.rules
Fixes: https://github.com/ricardoasmarques/ceph-dev-docker/issues/80
Signed-off-by: Stephan Müller <smueller@suse.com>
> Fixes prometheus rule expressions

- shared/bin/build-frontend.sh
> Build en-US language

- shared/bin/build-frontend.sh
> Use "npm ci" in all scripts

- Dockerfile
> Fix missing rpmspec

- Dockerfile
- setup.sh
This will allow the dashboard to list devices and display its smartctl data.
> Allow docker to access host devices

- shared/bin/start-ceph.sh
After https://github.com/ceph/ceph/pull/30961
> Configure dashboard log

- README.md
> Add instructions on who to configure Prometheus API

- Dockerfile
We don't need to merge it, it might just come in handy to be used temporarily.
Signed-off-by: Patrick Seidensal <pseidensal@suse.com>
> Works around issue with scipy in `diskprediction_local` module

- shared/bin/start-ceph.sh
> Set logging and debug mode after Octopus only

- mimic.Dockerfile
> Fix mimic dockerfile

- octopus.Dockerfile
- setup.sh
> Add octopus dockerfile

- octopus.Dockerfile
> Add missing packages to octopus dockerfile

- Dockerfile
> Add Cypress support

- octopus.Dockerfile
> Add Cypress to octopus

- shared/bin/fetch-pr.sh
> Add new fetch-pr.sh script

- shibboleth/Dockerfile
> Fix Shibboleth dockerfile

- shared/bin/setup-cephadm.sh
Otherwise it is not possible to deploy services.
> Disable cephadm stray warnings
