- Dockerfile
- README.md
- bash.bashrc
- setup-ceph.sh
by an automatic installation of dependecies as well as providing a setup
routine for the clone and build process of Ceph.
This is the stripped-down version without the adaptation to switch to ZSH.
It also includes a few minor bug fixes like installing the `ss` and `ifconfig` tools which enable `vstart.sh` to determine the IP/host name correctly.
> Reduce necessary user interaction

- Dockerfile
- setup-ceph.sh
* `python-devel` has been removed and trying to install it leads to an
error.
* `python2-Cython` is required to compile Ceph and
* `python2-PrettyTable` is required for running Ceph commands.
Using more `RUN` statements enables the Docker cache for each statement. This will speed up the rebuild process of the Docker image in case of failures.
> Update dependencies in `Dockerfile`

- Dockerfile
Provides the `killall` binary which is now used by `tox.`
> Add `psmisc` package to be able to run `tox`

- README.md
Added background information about `vstart.sh`, emphasized that
enabling debug mode generates large amounts of log files.
> Updated README.md: added info about vstart.sh

- Dockerfile
Remove the additional `security` zypper repository and explicit installation of `oath-toolkit` again. The package has now been added to Tumbleweed (see https://build.opensuse.org/request/show/595675),
and the package gets installed by `install-deps.sh` included in the Ceph git repo.
> Dockerfile: remove oath-toolkit installation

- README.md
- docker-compose.yml
- shibboleth/Dockerfile
- shibboleth/files/jetty-ssl-context.xml
- shibboleth/files/ldap.properties
- shibboleth/files/metadata-providers.xml
- shibboleth/files/shibboleth2.xml
- shibboleth/files/start.sh
This PR adds a new container that deploys a shibboleth Identity Provider (IDP) and an apache2 configured with the shibboleth Service Provider (SP) to allow the testing of the IDP.
The IDP is configured to use the LDAP server that is deployed by the openldap container.
After the shibboleth container is started you can access `http://localhost:9080/Shibboleth.sso/Login` to preform the login. If the user is not authenticated yet, it will be redirected to the IDP SSO page.
In the SSO page, you can use the "admin" user credentials configured in LDAP to authenticate.
> shibboleth IDP and SP docker container

- bin/setup-ceph.sh
with `bin/setup-ceph.sh`. This change has gotten neccessary due to a
change in `vstart_runner.sh` which now requires the `ceph-dencoder`
binary to be present when it checks for required dependecies. Otherwise
it'll complain and abort when running `run-backend-api-tests.sh`.
> Build test dependecies when building Ceph

- README.md
- Add to the documentation that the Grafana data directory needs to be
created alongside the required permissions.
- Fix a section header.
- Add a section header for the troubleshooting entry.
- Add URLs to services where they were missing.
> Improve the README of the configuration of Grafana

- README.md
The link was broken (due to a rename of the original section)
> Fix Grafana link (anchor)

- shibboleth/Dockerfile
Fixes running ``docker-compose up`` otherwise it'll throw an error because shibboleth version 3.3.3 is no longer the latest version.
> Point to the latest shibboleth version 3.4.1

- README.md
- alertmanager/config.yml
- docker-compose.yml
- prometheus/alert.rules
- prometheus/prometheus.yml
Included some example rules, with one that is always failing, in order
to test alerts easily. Extended the documentation on how to use it.
Fixes: https://tracker.ceph.com/issues/37585
Signed-off-by: Stephan Müller <smueller@suse.com>
> mgr/dashboard/docker: Add the Prometheus Alertmanager

- Dockerfile
Building the ceph-dev-docker container failed with an installation
error: "No provider of 'librados2' found.". Fixed by removing the
package from the list of packages to be installed.
> Dockerfile: removed installation of librados2

- docker-compose.yml
Also updated image names to match the naming convention in the [upstream installation instructions](https://prometheus.io/docs/prometheus/latest/installation/#using-docker)
> docker-compose.yml: fixed permission issues when starting prometheus 2.6 container

- shared/bin/create-dashboard-rgw-user.sh
- shared/bin/start-ceph.sh
Move dashboard RGW configuration into a
separate file `create-dashboard-rgw-user.sh`
in order to be able to run this step separately.
> start-ceph.sh: split out RGW configuration

- shared/bin/create-dashboard-rgw-user.sh
Improved `create-dashboard-rgw-user.sh` by removing a superflouous `sed` call.
> Simplify RGW user creation

- shared/bin/setup-ceph.sh
- shared/zsh/.zshrc
Setting `SOURCE_DATE_EPOCH` to `0` had some weird side effects when building Python modules. Setting the date to `946684800` (2001-01-01) in `.zshrc` and removing the duplicate definition `setup-ceph.sh` should fix this.
> Set SOURCE_DATE_EPOCH to 946684800 in .zshrc

- README.md
- mimic.Dockerfile
- setup.sh
- shared/bin/setup-ceph.sh
- shared/docker/install-chrome.sh
- shared/docker/install-omz.sh
- shared/zsh/.zshrc
- shared/zsh/dash.plugin.zsh
* Removed gcc7 scripts, leap:15 still uses that version and
nautilus doesn't require it.
* Extracted chrome and zsh installation to separate scripts.
* Setup.sh now creates different docker images for each release.
`Signed-off-by: Tiago Melo <tmelo@suse.com>`
> Add mimic dockerfile

- alertmanager/config.yml
- prometheus/alert.rules
- prometheus/prometheus.yml
Adapt configurations to get the prometheus-webhook-snmp Prometheus Alertmanager webhook working.
> Modify configuration for prometheus-webhook-snmp

- shared/bin/npm-start.sh
> Use "npm ci" to prevent installing new updates during development

- Dockerfile
- shared/bin/setup-ceph.sh
SPDK is not working with gcc9, so we have to downgrade to v8,
install-deps.sh was failing because python2-virtualenv was missing.
> Fix python2 and gcc9 problems

- grafana/grafana.ini
Update default configuration file from grafana/grafana:6.2.1
Starts from Grafana 6.2.0, embedding dashboards in iframes is not
allowed by default. Enable this in configuration file.
> Update Grafana config and allow embedding in iframe

- Dockerfile
- shared/bin/setup-ceph.sh
Problem with SPDK has been fix in ceph.
gcc8 was now causing problems with RocksDB.
> Remove gcc9 temporary fix

- README.md
- docker-compose.yml
- haproxy/haproxy.cfg
> Add HAProxy container for simple HA testing

- shared/zsh/.zshrc
This will allow us to run npm ci without having to interact with the cli.
> Add NG_CLI_ANALYTICS environment variable

- Dockerfile
python3-scipy needs to be installed for loading diskprediction_local
module. This fixes run-frontend-e2e-tests.sh failure in container.
See https://tracker.ceph.com/issues/43230.
*NOTE*: This only applies to new created container, for existing one simply run:
```
zypper in python3-scipy
```
> Install scipy for diskprediction_local module

- Dockerfile
python3-remoto is required to run cephadm module.
> Install remoto for cephadm module

- README.md
When I tried running the command as it was, it failed because of the
single quotes
Signed-off-by: Sebastian Krah <skrah@suse.com>
> Remove single quotes

- shared/bin/setup-nfs.sh
- shared/bin/start-ceph.sh
To install NFS Ganesha run the 'setup-nfs.sh' script. This will install all necessary packages. The 'start-ceph.sh' script will automatically take care to setup vstart correctly if the NFS packages are installed.
> Add script to install NFS Ganesha easily in the Docker container.

- Dockerfile
Update dependency to python3-virtualenv because it's no longer available in tumbleweed.
Signed-off-by: Tatjana Dehler <tdehler@suse.com>
> Update python2-virtualenv dependency to python3

- nautilus.Dockerfile
- setup.sh
If the local cached image is out of date for some time, it might cause
problem when updating packages.
Nautilus' base image is updated to opensuse/leap:15.1 since 15.0 is eol.
> Always pull images when building images.

- README.md
- shared/bin/setup-nfs.sh
- shared/bin/start-ceph.sh
- `nfs-ganesha-rados-urls` package is required to create exports.
- Update README.md: required step to bring up NFS support.
> Add a missing package for nfs-ganesha

- shared/bin/npm-start.sh
Currently is not possible to access angular from a different machine.
> Allow access to angular remotely

- shared/docker/install-omz.sh
- shared/zsh/.zshrc
- shared/zsh/binds.plugin.zsh
This allows us to call 'ceph' and 'npm' from any directory and they will be
executed in the proper directory.
'ceph' will be executed in '/ceph/build'.
'npm' will first activate the nodeenv and
then execute in 'dashboard/frontend'.
Signed-off-by: Stephan Müller <smueller@suse.com>
> Add binds for ceph and npm

- README.md
- setup.sh
- shared/bin/setup-cephadm.sh
The helper script `setup-cephadm.sh` will configure the system to be able to use the `src/pybind/mgr/cephadm` Vagrant box.
> Setup the container to be able to use the cephadm Vagrant box

- README.md
Currently my build with this fails because I run out of memory with my 16 cores. This small adjustment makes it possible to define the number of build jobs done concurrently via an argument. Comment in the script as documentation was also added.
> Add number of build jobs option to the script

- shared/bin/start-ceph.sh
The NFS variable change in the vstart.sh had been [backported to octopus](https://github.com/ceph/ceph/commit/2fa01181ccdbecd127387d12f1ff4f98d7330940).
Adapt to this change. Ceph version detection is more reliable now.
> start-ceph.sh: enable NFS in octopus

- shared/bin/reload-cephadm.sh
Add helper script to reload the `cephadm` manager module.
> Add command to reload the cephadm manager module.

- shared/bin/create-dashboard-rgw-user.sh
The way to set RGW keys is changed after https://github.com/ceph/ceph/pull/38284.
Store the keys in a config folder and read the keys from there.
The original method is still kept as a fallback.
> Read RGW keys from files
